name: "test Environment variable"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string

jobs:
  gridai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@main
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          export COLUMNS={512}
          export RUN_STATUS_T1=$(grid status ubiquitous-sturgeon-427 | awk '{print $2 "," $6}')
          echo $RUN_STATUS_T1
          export RUN_STATUS_T2=$(grid status ubiquitous-sturgeon-427 | awk '{print $2 "," $6}' | grep ubiquitous-…)
          echo $RUN_STATUS_T2
          export RUN_STATUS=$(grid status ubiquitous-sturgeon-427 | awk '{print $2 "," $6}' | grep ubiquitous-… | awk -F, '{print $2}')
          echo $RUN_STATUS
          export RUN_STATUS1=$(grid status ubiquitous-sturgeon-427)
          export RUN_STATUS2=$(RUN_STATUS1 | grep ubiquitous-sturgeon-427 | awk '{print $6}')
          echo "RUN_STATUS $RUN_STATUS2"
      
          ls -al
        shell: bash
        
 
