name: "test Environment variable"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string

jobs:
  gridai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@main
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          export COLUMNS={512}
          # export RUN_STATUS_T1=$(grid status ${{ secrets.GRIDAI_RUNNAME }}  | grep ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}')
          # echo $RUN_STATUS_T1
          # export RUN_STATUS_T2=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}' | grep ${{ secrets.GRIDAI_RUNNAME }})
          # echo $RUN_STATUS_T2
          export RUN_STATUS=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}' | grep ${{ secrets.GRIDAI_RUNNAME }} | awk -F, '{print $2}')
          echo $RUN_STATUS
          export RUN_DURATION=$(grid status ${{ secrets.RUN_NAME }} | grep ${{ secrets.RUN_NAME }} | awk '{print $10}'| cut -d 'd' -f 1) 
          echo $RUN_DURATION
        shell: bash
        
 
