name: "test Environment variable"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string

jobs:
  gridai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          export RUN_STATUS="$(grid status ubiquitous-sturgeon-427 | grep ubiquitous-sturgeon-427 | awk '{print $6}')"
          echo "RUN_STATUS $RUN_STATUS"
          export RUN_STATUS1=$(grid status ubiquitous-sturgeon-427)
          echo "RUN_STATUS $RUN_STATUS1"
          export ENV_PWD='pwd'
          export ENV2=$($ENV_PWD | grep work)
          echo ENV $ENV2
          export ENV_PWD=$(`pwd` | grep work)
          echo ENV_pwd $ENV_PWD
          ls -al
        shell: bash
