name: "test Run Stop"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
jobs:
  gridai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@main
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
      - id: gridai-prunname
        run: |
           export PART_NAME=$(echo ${{ secrets.GRIDAI_RUNNAME }} | cut -d '-' -f 1 )
           echo "runname: $PART_NAME"
      - id: gridai-status
        run: |
          export COLUMNS={512}
          sleep 30
          export RUN_STATUS=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}' | grep $PART_NAME | cut -d ',' -f 2 )
          echo "status: $RUN_STATUS"
        shell: bash
