name: "test Run Stop"

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
jobs:
  gridai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@main
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
      - id: gridai-prunname
        run: |
           export P_RUN_NAME=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}' | cut -d '-' -f 1 )
           echo $P_RUN_NAME
      - id: gridai-status
        run: |
          export COLUMNS={512}
          sleep 30
          export RUN_STATUS=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}' )
          echo $RUN_STATUS
          export RUN_STATUS2=$(grid status ${{ secrets.GRIDAI_RUNNAME }} | awk '{print $2 "," $6}')
          echo $RUN_STATUS2
        shell: bash
