name: "test wandb"

on:
  workflow_dispatch:
    inputs:
      grid-args:
        required: true
        default: --config config.yml --instance_type g4dn.xlarge
        description: test wandb

jobs:
  gridai-wandb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@main --add-module-version 0.8.15
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
              
      - id: gridai-obj-status
        run: |
          # failed can flipped to running.  check 3 times for flip flop.
          pwd
          ls -al
          grid run ${{github.event.inputs.grid-args}} run.py
        shell: bash
